[phases.setup]
nixPkgs = ["nodejs-18_x", "postgresql"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci --only=production"]

[phases.build]
dependsOn = ["install"]
cmds = [
  "npm install --include=dev",
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"